events { worker_connections 1024; }

http {
  server {
    listen 80;
    server_name nc.groupe-nissi.com api.nc.groupe-nissi.com;

    location /.well-known/acme-challenge/ {
      root /var/www/certbot;
    }

    location / {
      return 200 'NISSI - SSL en cours de configuration';
      add_header Content-Type text/plain;
    }
  }
}
